//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: login.proto
namespace PBMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2S_LoginRequest")]
  public partial class C2S_LoginRequest : global::ProtoBuf.IExtensible
  {
    public C2S_LoginRequest() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2C_LoginSuccess")]
  public partial class S2C_LoginSuccess : global::ProtoBuf.IExtensible
  {
    public S2C_LoginSuccess() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _profess;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"profess", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int profess
    {
      get { return _profess; }
      set { _profess = value; }
    }
    private int _sex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private int _grade;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"grade", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int grade
    {
      get { return _grade; }
      set { _grade = value; }
    }
    private int _life;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"life", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int life
    {
      get { return _life; }
      set { _life = value; }
    }
    private int _magic;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"magic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int magic
    {
      get { return _magic; }
      set { _magic = value; }
    }
    private int _exp;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _attackmin;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"attackmin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attackmin
    {
      get { return _attackmin; }
      set { _attackmin = value; }
    }
    private int _attackMax;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"attackMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attackMax
    {
      get { return _attackMax; }
      set { _attackMax = value; }
    }
    private int _magicAttackMin;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"magicAttackMin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int magicAttackMin
    {
      get { return _magicAttackMin; }
      set { _magicAttackMin = value; }
    }
    private int _magicAttackMax;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"magicAttackMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int magicAttackMax
    {
      get { return _magicAttackMax; }
      set { _magicAttackMax = value; }
    }
    private int _defence;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"defence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int defence
    {
      get { return _defence; }
      set { _defence = value; }
    }
    private int _magicDefence;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"magicDefence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int magicDefence
    {
      get { return _magicDefence; }
      set { _magicDefence = value; }
    }
    private int _dodge;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"dodge", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dodge
    {
      get { return _dodge; }
      set { _dodge = value; }
    }
    private int _endurance;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"endurance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int endurance
    {
      get { return _endurance; }
      set { _endurance = value; }
    }
    private int _agile;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"agile", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int agile
    {
      get { return _agile; }
      set { _agile = value; }
    }
    private int _moveSpeed;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"moveSpeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int moveSpeed
    {
      get { return _moveSpeed; }
      set { _moveSpeed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: register.proto
namespace PBMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2S_RegisterRequest")]
  public partial class C2S_RegisterRequest : global::ProtoBuf.IExtensible
  {
    public C2S_RegisterRequest() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private int _telephone;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"telephone", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int telephone
    {
      get { return _telephone; }
      set { _telephone = value; }
    }
    private string _identity;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"identity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string identity
    {
      get { return _identity; }
      set { _identity = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}